/**
 * Default Feature Configuration
 *
 * Pre-defined feature extraction configurations for common identity matching scenarios.
 */

import type { FeatureExtractionConfig } from '../types'

/**
 * Default feature configuration for person/customer matching.
 *
 * This configuration extracts features from common person identity fields:
 * - firstName: Name similarity (Jaro-Winkler, Soundex, exact match)
 * - lastName: Name similarity with higher weight (Jaro-Winkler, Soundex, exact match)
 * - email: String similarity (Levenshtein, exact match)
 * - phone: String similarity (Levenshtein, exact match)
 * - dateOfBirth: Date comparison (exact match, date difference)
 * - address: Address similarity (Levenshtein, Jaro-Winkler)
 * - ssn: Exact match only with highest weight
 */
export const DEFAULT_PERSON_FEATURE_CONFIG: FeatureExtractionConfig = {
  fields: [
    {
      field: 'firstName',
      extractors: ['jaroWinkler', 'soundex', 'exact'],
      weight: 1.0,
      includeMissingIndicator: true,
    },
    {
      field: 'lastName',
      extractors: ['jaroWinkler', 'soundex', 'exact'],
      weight: 1.2,
      includeMissingIndicator: true,
    },
    {
      field: 'email',
      extractors: ['levenshtein', 'exact'],
      weight: 1.5,
      includeMissingIndicator: true,
    },
    {
      field: 'phone',
      extractors: ['levenshtein', 'exact'],
      weight: 1.3,
      includeMissingIndicator: true,
    },
    {
      field: 'dateOfBirth',
      extractors: ['exact', 'dateDiff'],
      weight: 1.4,
      includeMissingIndicator: true,
    },
    {
      field: 'address',
      extractors: ['levenshtein', 'jaroWinkler'],
      weight: 0.8,
      includeMissingIndicator: true,
    },
    {
      field: 'ssn',
      extractors: ['exact'],
      weight: 2.0,
      includeMissingIndicator: true,
    },
  ],
  normalize: true,
}

/**
 * Feature names generated by the default person feature config.
 * Order matches the order in which features are extracted.
 */
export const DEFAULT_PERSON_FEATURE_NAMES: string[] = [
  // firstName features (3 extractors + 1 missing indicator)
  'firstName_jaroWinkler',
  'firstName_soundex',
  'firstName_exact',
  'firstName_missing',
  // lastName features (3 extractors + 1 missing indicator)
  'lastName_jaroWinkler',
  'lastName_soundex',
  'lastName_exact',
  'lastName_missing',
  // email features (2 extractors + 1 missing indicator)
  'email_levenshtein',
  'email_exact',
  'email_missing',
  // phone features (2 extractors + 1 missing indicator)
  'phone_levenshtein',
  'phone_exact',
  'phone_missing',
  // dateOfBirth features (2 extractors + 1 missing indicator)
  'dateOfBirth_exact',
  'dateOfBirth_dateDiff',
  'dateOfBirth_missing',
  // address features (2 extractors + 1 missing indicator)
  'address_levenshtein',
  'address_jaroWinkler',
  'address_missing',
  // ssn features (1 extractor + 1 missing indicator)
  'ssn_exact',
  'ssn_missing',
]

/**
 * Total number of features in the default person feature config
 */
export const DEFAULT_PERSON_FEATURE_COUNT = DEFAULT_PERSON_FEATURE_NAMES.length

/**
 * Minimal feature configuration for basic name + email matching.
 * Useful when only basic fields are available.
 */
export const MINIMAL_FEATURE_CONFIG: FeatureExtractionConfig = {
  fields: [
    {
      field: 'firstName',
      extractors: ['jaroWinkler', 'exact'],
      weight: 1.0,
      includeMissingIndicator: true,
    },
    {
      field: 'lastName',
      extractors: ['jaroWinkler', 'exact'],
      weight: 1.0,
      includeMissingIndicator: true,
    },
    {
      field: 'email',
      extractors: ['levenshtein', 'exact'],
      weight: 1.5,
      includeMissingIndicator: true,
    },
  ],
  normalize: true,
}

/**
 * Feature names for minimal config
 */
export const MINIMAL_FEATURE_NAMES: string[] = [
  'firstName_jaroWinkler',
  'firstName_exact',
  'firstName_missing',
  'lastName_jaroWinkler',
  'lastName_exact',
  'lastName_missing',
  'email_levenshtein',
  'email_exact',
  'email_missing',
]

/**
 * Extended feature configuration with additional identity fields.
 * Includes middle name, suffix, alternate names, and multiple addresses.
 */
export const EXTENDED_FEATURE_CONFIG: FeatureExtractionConfig = {
  fields: [
    // Primary name fields
    {
      field: 'firstName',
      extractors: ['jaroWinkler', 'soundex', 'metaphone', 'exact'],
      weight: 1.0,
      includeMissingIndicator: true,
    },
    {
      field: 'middleName',
      extractors: ['jaroWinkler', 'soundex', 'exact'],
      weight: 0.6,
      includeMissingIndicator: true,
    },
    {
      field: 'lastName',
      extractors: ['jaroWinkler', 'soundex', 'metaphone', 'exact'],
      weight: 1.2,
      includeMissingIndicator: true,
    },
    {
      field: 'suffix',
      extractors: ['exact'],
      weight: 0.3,
      includeMissingIndicator: true,
    },
    // Contact fields
    {
      field: 'email',
      extractors: ['levenshtein', 'exact'],
      weight: 1.5,
      includeMissingIndicator: true,
    },
    {
      field: 'phone',
      extractors: ['levenshtein', 'exact'],
      weight: 1.3,
      includeMissingIndicator: true,
    },
    {
      field: 'alternatePhone',
      extractors: ['levenshtein', 'exact'],
      weight: 0.8,
      includeMissingIndicator: true,
    },
    // Dates
    {
      field: 'dateOfBirth',
      extractors: ['exact', 'dateDiff'],
      weight: 1.4,
      includeMissingIndicator: true,
    },
    // Address fields
    {
      field: 'address',
      extractors: ['levenshtein', 'jaroWinkler'],
      weight: 0.8,
      includeMissingIndicator: true,
    },
    {
      field: 'city',
      extractors: ['jaroWinkler', 'exact'],
      weight: 0.5,
      includeMissingIndicator: true,
    },
    {
      field: 'state',
      extractors: ['exact'],
      weight: 0.4,
      includeMissingIndicator: true,
    },
    {
      field: 'zipCode',
      extractors: ['levenshtein', 'exact'],
      weight: 0.6,
      includeMissingIndicator: true,
    },
    // Identity numbers
    {
      field: 'ssn',
      extractors: ['exact'],
      weight: 2.0,
      includeMissingIndicator: true,
    },
    {
      field: 'driverLicense',
      extractors: ['exact'],
      weight: 1.8,
      includeMissingIndicator: true,
    },
  ],
  normalize: true,
}

/**
 * Feature configuration for patient/healthcare matching.
 * Optimized for healthcare identity matching requirements.
 */
export const PATIENT_FEATURE_CONFIG: FeatureExtractionConfig = {
  fields: [
    // Patient name fields - healthcare often has more name variants
    {
      field: 'firstName',
      extractors: ['jaroWinkler', 'soundex', 'metaphone', 'exact'],
      weight: 1.0,
      includeMissingIndicator: true,
    },
    {
      field: 'middleName',
      extractors: ['jaroWinkler', 'exact'],
      weight: 0.5,
      includeMissingIndicator: true,
    },
    {
      field: 'lastName',
      extractors: ['jaroWinkler', 'soundex', 'metaphone', 'exact'],
      weight: 1.2,
      includeMissingIndicator: true,
    },
    // Date of birth is critical in healthcare
    {
      field: 'dateOfBirth',
      extractors: ['exact', 'dateDiff'],
      weight: 2.0,
      includeMissingIndicator: true,
    },
    // Gender - simple exact match
    {
      field: 'gender',
      extractors: ['exact'],
      weight: 0.8,
      includeMissingIndicator: true,
    },
    // Medical record numbers
    {
      field: 'mrn',
      extractors: ['exact', 'levenshtein'],
      weight: 2.5,
      includeMissingIndicator: true,
    },
    // SSN for US patients
    {
      field: 'ssn',
      extractors: ['exact'],
      weight: 2.0,
      includeMissingIndicator: true,
    },
    // Contact
    {
      field: 'phone',
      extractors: ['levenshtein', 'exact'],
      weight: 1.0,
      includeMissingIndicator: true,
    },
    // Address
    {
      field: 'address',
      extractors: ['levenshtein', 'jaroWinkler'],
      weight: 0.6,
      includeMissingIndicator: true,
    },
    {
      field: 'zipCode',
      extractors: ['exact'],
      weight: 0.5,
      includeMissingIndicator: true,
    },
  ],
  normalize: true,
}

/**
 * Get the feature configuration by name
 */
export function getFeatureConfig(
  name: 'person' | 'minimal' | 'extended' | 'patient'
): FeatureExtractionConfig {
  switch (name) {
    case 'person':
      return DEFAULT_PERSON_FEATURE_CONFIG
    case 'minimal':
      return MINIMAL_FEATURE_CONFIG
    case 'extended':
      return EXTENDED_FEATURE_CONFIG
    case 'patient':
      return PATIENT_FEATURE_CONFIG
    default:
      return DEFAULT_PERSON_FEATURE_CONFIG
  }
}

/**
 * Calculate the total number of features for a given config
 */
export function calculateFeatureCount(config: FeatureExtractionConfig): number {
  let count = 0
  for (const field of config.fields) {
    // Add extractor count
    count += field.extractors.length
    // Add missing indicator if enabled (defaults to true)
    if (field.includeMissingIndicator !== false) {
      count += 1
    }
  }
  return count
}

/**
 * Generate feature names for a given config
 */
export function generateFeatureNames(
  config: FeatureExtractionConfig
): string[] {
  const names: string[] = []
  for (const field of config.fields) {
    for (const extractor of field.extractors) {
      names.push(`${field.field}_${extractor}`)
    }
    if (field.includeMissingIndicator !== false) {
      names.push(`${field.field}_missing`)
    }
  }
  return names
}
